In [1]:
import numpy as np
list1=[10,20,30]
list2=[30,40,50]
print(list1+list2)

[10, 20, 30, 30, 40, 50]


In [2]:
list2=4
print(list1*list2)

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]


In [3]:
l1=np.array([1,2,3])
print(l1)

[1 2 3]


In [4]:
l2=(3)
print(l1*l2)

[3 6 9]


In [5]:
a=[30,40,20,40,30]
arr=np.array(a)
print(arr)

[30 40 20 40 30]


In [6]:
print(arr.shape) #rows,columns

(5,)


In [7]:
print(len(arr)) #no of nested values

5


In [8]:
print(np.size(arr)) #no of elements

5


In [9]:
print(type(arr)) #datatype of variable

<class 'numpy.ndarray'>


In [10]:
print(arr.dtype) #datatype of array

int32


In [11]:
print(arr.astype(str)) #conversion of datatype

['30' '40' '20' '40' '30']


In [12]:
#Mathematical operations and Functions on Arrays
import numpy as np
arr=np.array([1,2,3,4,5])
arr2=np.array([4,5,6,7,8])
print(arr+arr2)

[ 5  7  9 11 13]


In [13]:
print(np.add(arr,arr2)) #np.add

[ 5  7  9 11 13]


In [14]:
print(np.subtract(arr,arr2)) #np.subtract

[-3 -3 -3 -3 -3]


In [15]:
print(np.multiply(arr,arr2)) #np.multiply

[ 4 10 18 28 40]


In [16]:
print(np.divide(arr,arr2)) #np.divide

[0.25       0.4        0.5        0.57142857 0.625     ]


In [17]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [18]:
np.exp(a)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [19]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [20]:
print(np.power(a,b))

[[    1    64]
 [ 2187 65536]]


In [21]:
#splitting array
a=[1,2,3]
b=[4,5,6]
print(a+b)

[1, 2, 3, 4, 5, 6]


In [22]:
#concatenate

arr=np.array([[1,2,3],[7,8,9]])
arr2=np.array([[4,5,6],[10,11,12]])
print(np.concatenate([arr,arr2]))

[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [23]:
print(np.concatenate([arr,arr2],axis=1))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [24]:
print(np.hstack([arr,arr2])) #horizontal Concatenation

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [25]:
 print(np.vstack([arr,arr2])) #Vertical Concatenation

[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]


In [26]:
a=np.array([1,2,3,4,5,6])
b=np.array_split(a,3)
print(np.array_split(a,3))
print(b[1])

[array([1, 2]), array([3, 4]), array([5, 6])]
[3 4]


In [27]:
#adding and removig elements
a=np.array([20,40,60,80])
print(np.append(a,90))

[20 40 60 80 90]


In [28]:
a=np.array([[20,40],[60,80]])
print(np.append(a,90))

[20 40 60 80 90]


In [29]:
a=np.array([[20,40],[60,80]])
print(np.append(a,[90,100]))

[ 20  40  60  80  90 100]


In [30]:
print(np.insert(a,1,50)) #array,index,element

[20 50 40 60 80]


In [31]:
print(np.insert(a,1,[50,60],axis=0))

[[20 40]
 [50 60]
 [60 80]]


In [32]:
print(np.insert(a,1,[50],axis=0))

[[20 40]
 [50 50]
 [60 80]]


In [33]:
print(np.insert(a,[1,2],[50],axis=1))

[[20 50 40 50]
 [60 50 80 50]]


In [37]:
print(a)
print(np.delete(a,1,axis=1))

[[20 40]
 [60 80]]
[[20]
 [60]]


In [39]:
#sort, filter and serach
ar=np.array([[3,2,1,0,5],[2,5,1,0,3]])
print(np.sort(ar))

[[0 1 2 3 5]
 [0 1 2 3 5]]


In [41]:
arr=np.array([1,2,4,5,3])
s=np.where(arr==4)
print(s)

(array([2], dtype=int64),)


In [42]:
arr=np.array([1,2,4,5,3])
s=np.where(arr%2==0)
print(s)

(array([1, 2], dtype=int64),)


In [45]:
#searchsorted
arr=np.array([1,2,3,4,5])
ss=np.searchsorted(arr,2)
print(ss)

1


In [46]:
ar=np.array([20,30,40,50])
fa=[True,False,True,False]
new=ar[fa]
print(new)

[20 40]


In [47]:
ar=np.array([20,30,40,50])
fa=[True,False,False,False]
new=ar[fa]
print(new)

[20]


In [48]:
fa=ar>35
new=ar[fa]
print(new)

[40 50]


In [49]:
fa=ar%2==0
new=ar[fa]
print(new)

[20 30 40 50]


In [56]:
#aggregating Functions in numpy
a=np.array([20,40,60,70])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.size(a))
print(np.mean(a))
print(np.cumsum(a)) #cummalative sum
print(np.cumprod(a)) #cummalative product


190
20
70
4
47.5
[ 20  60 120 190]
[     20     800   48000 3360000]


In [71]:
a=[100,150,199,200,250,130]
b=[10,50,30,40,30,10]
price=np.array(a)
quantity=np.array(b)
print(price,quantity)
print(np.sum(price))
c=np.cumprod([price,quantity],axis=0)
print(c[1].sum())

[100 150 199 200 250 130] [10 50 30 40 30 10]
1029
31270


In [75]:
#Statistical function in numpy
import statistics as stats
baked_food=[200,300,150,130,200,280,170,188]
a=np.array(baked_food)
print(np.mean(baked_food)) # sum of all values/no of values
print(np.median(baked_food)) #central value after sorting
print(stats.mode(baked_food)) #there is no mode in numpy so we use statistics library
print(np.std(baked_food)) #standard deviation used quality assurance
print(np.var(baked_food)) #variance

202.25
194.0
200
55.68157235567257
3100.4375


In [79]:
# -1 represents inversely proportional relationship
# 1 represents proportional relationship
# 0 means no relationship
tobacco_consumption=[30,50,10,30,50,40]
deaths=[100,120,70,100,120,112]
print(np.corrcoef([tobacco_consumption,deaths]))

[[1.         0.99015454]
 [0.99015454 1.        ]]


In [80]:
price=[300,100,350,150,200]
sales=[10,20,7,17,3]
print(np.corrcoef([price,sales]))

[[ 1.         -0.66621445]
 [-0.66621445  1.        ]]
