In [1]:
import numpy as np
X=np.array([[-1,-1],[-2,-1],[1,1],[2,1]])
y=np.array([1,1,2,2])
from sklearn.svm import SVC
clf=SVC()
clf.fit(X,y)
print(clf.predict([[-0.8,-1]]))

[1]


# Implementing SVC

In [45]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

iris=load_iris()
X=iris.data
y=iris.target

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

svm_model=SVC(kernel='linear',C=1.0,random_state=42)

svm_model.fit(X_train,y_train)

y_pred=svm_model.predict(X_test)

accuracy=accuracy_score(y_test,y_pred)
conf_matrix=confusion_matrix(y_test,y_pred)
class_report=classification_report(y_test,y_pred)

print('Accuracy:',accuracy)
print('Confusion Matrix:\n',conf_matrix)
print('Classification Report:\n',class_report)

new_sample=np.array([[5.1,3.5,1.4,0.2]])
prediction=svm_model.predict(new_sample)
print('Predicted class for the new sample:',prediction)

Accuracy: 1.0
Confusion Matrix:
 [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Predicted class for the new sample: [0]


# Implemeanting SVR

In [38]:
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.datasets import fetch_california_housing
california = fetch_california_housing()
X = california.data
y = california.target 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

svr_model = SVR(kernel='rbf', C=1.0, epsilon=0.1)

svr_model.fit(X_train, y_train)

y_pred = svr_model.predict(X_test)

mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("Mean Squared Error:", mse)
print("R-squared:", r2)

new_sample = np.array([[8.3252, 41.0, 6.9841, 1.02381, 322.0, 2.5556, 37.88, -122.23]])  # Example sample for prediction
prediction = svr_model.predict(new_sample)
print("Predicted value for the new sample:", prediction)

Mean Squared Error: 1.3489971413208706
R-squared: -0.027775938647489617
Predicted value for the new sample: [1.80104449]
